name: CI

on:
  workflow_call: # From .github/workflows/Release.yml
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  all-jobs:
    if: always() # Otherwise this job is skipped if the matrix job fails
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
      - run: jq --exit-status 'all(.result == "success")' <<< '${{ toJson(needs) }}'

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-deny
      - run: ./scripts/lint.sh

  test:
    strategy:
      fail-fast: false
      matrix:
        variant:
          - { name: Ubuntu,  os: ubuntu-latest,  }
          # TODO: Enable once users on these platforms show up
          #- { name: macOS,   os: macos-latest,   }
          #- { name: Windows, os: windows-latest, }
    name: test (${{ matrix.variant.name }}
    runs-on: ${{ matrix.variant.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - run: ./scripts/test.sh
